#!/usr/bin/env perl
# Build a number of files/directories with Nancy

use 5.10.0;
use strict;
use warnings;

use File::Basename;
use File::Path qw(make_path);
use Text::ParseWords;

# Read and process arguments
my ($src, $template, $pages) = @ARGV;
my @pages = shellwords($pages);

# Run test
for my $page (@pages) {
  my $err;
  my @nancy_cmd = ($ENV{NANCY}, "--verbose", "--root=$src", "--output=dest/$page", $template, $page);
  #unshift @nancy_cmd, "perl", "-wMDevel::SimpleTrace";
  my $dir = "dest/$page";
  make_path(dirname($dir), {error => \$err});
  die "Error creating `$dir'" if @$err;
  system(@nancy_cmd) == 0 or die "Problem building `$page'\n";
}
