#!/usr/bin/env perl
# Run a test for Nancy

use 5.10.0;
use strict;
use warnings;

use File::Path qw(remove_tree);

# Read and process arguments
my ($src, $template, $expected, $pages) = @ARGV;

# Run test
my $err;
remove_tree("dest", {error => \$err});
die "Error removing dest" if @$err;
my @cmd;
@cmd = defined($pages) ? ("./build-things", $src, $template, $pages)
  : ("./build-tree", $src, $template, "dest");
system(@cmd) == 0 or die "Test in `$src' failed to run\n";
system("diff", "-Nur", $expected, "dest") == 0 or die "Test in \`$src' produced incorrect output\n";
