#!/bin/sh
# Run this file to set up repository's git config for auto-versioning of scripts
git config --local include.path '../.gitconfig'
# Run the filters immediately
rm .git/index
git checkout HEAD -- "$(git rev-parse --show-toplevel)"
